### ISSUE TITLE
::status must return a relationship instance

### ISSUE THREAD

**Issue by ahmad96hijazi** [spatie/laravel-model-status#108]
it is not clear what is the error any help on it please but all model that use HasStatuses suddenly give that error

![image](https://github.com/spatie/laravel-model-status/assets/40335765/332a7117-e022-4d35-b31e-a8fa859b9953)

**Comment by ahmad96hijazi** [comment]
fixed thanks

**Comment by Luukdewaaier** [comment]
@ahmad96hijazi How did you resolve this issue?
