### ISSUE TITLE
Implement enum based statuses

### ISSUE THREAD

**Issue by MhdGhaithAlhelwany** [spatie/laravel-model-status#118]
I've used this package before, it's great, but something I always end up doing is wrapping it around a different trait to add more restriction to how my statuses are set. 

Would it be a good idea if a solution that uses PHP Enums was used, to apply this restriction? 
Here's an example usage

```php
$post->setStatus(PostStatus::PENDING, 'needs verification');
$post->status; //returns PostEnum Instance
```

I'm willing to work on this feature.

**Comment by freekmurze** [comment]
Yes, feel free to send a PR. Make sure to add tests and update the readme

**Comment by MhdGhaithAlhelwany** [comment]
Should i work on an alternative trait to HasStatuses, for example HasStrictStatuses, and keep the original trait? or should i replace the original one? @freekmurze
