### ISSUE TITLE
Upgrade from 1.15.* to 1.16.0 is a breaking change

### ISSUE THREAD

**Issue by cjmcdonn** [spatie/laravel-model-status#123]
The upgrade from 1.15.* to 1.16.0 is a breaking change, at least for me. The change to Enums seems like a pretty massive overhaul. It might be too late now but this might be better released as 2.0.0.

**Comment by Maxoulak** [comment]
I agree. Use native php enums is a great improvement (thanks for that), but adding an abstract method to the `Spatie\ModelStatus\HasStatuses` trait is a breaking change.
Imo, I recommend to fix version to "~1.15.0" in your `composer.json` for now.

**Comment by freekmurze** [comment]
I've released 1.17 that contains the code of 1.15.

Apologies for the inconvenience.

**Comment by emielmolenaar** [comment]
No worries, thanks for the fix👍🏻

**Comment by cjmcdonn** [comment]
Thanks!
