### ISSUE TITLE
Any reason not to add an accessor?

### ISSUE THREAD

**Issue by hailwood** [spatie/laravel-model-status#16]
I note that we can use `$myModel->status()` to get the latest status,

Could we add a `getStatusAttribute()` function that would do the same as `->status()`, but would allow us to just to `$myModel->status` I believe this would play better with the $appends` property on Eloquent models as well.

Happy to contribute if approved.

**Comment by freekmurze** [comment]
I'm actually torn if `getStatusAttribute()` should return a `Status` or the `name` of a `Status`.

**Comment by hailwood** [comment]
I'm inclined to go with a `Status` purely based on needing the reason as well, otherwise We'd need to add a `getStatusReasonAttribute()` as well which I'm not a fan of.

What about adding a `__toString()` to `Status` that returns `$this->name` ?

That way in your blade templates you can do (assuming you've called `->setStatus('pending', 'awaiting payment')`)

```
{{ $item->status }} will output "pending"
{{ $item->status->name }} will also output "pending"
{{ $item->status->reason }} will output "awaiting payment"
```
```

**Comment by freekmurze** [comment]
@hailwood That's cool, might go for that. Thanks for the suggestion.

**Comment by TVke** [comment]
@hailwood the feature is present in the 1.0.5 branch. We are still working on another feature so after finishing that one it will be possible as you asked.
