### ISSUE TITLE
Properties?

### ISSUE THREAD

**Issue by llhilton** [spatie/laravel-model-status#19]
Wondering about the possibility of storing additional properties, not just a reason. I'm thinking similar to the properties of your activity log package. I'm not 100% sure if that's a better approach than others that you could take to accomplish the same thing (like a related table or something). The project I'm working on right now stores some additional information with some of the status changes. We don't need to search on it or anything, so having it pretty simple like the activity log properties would make sense. But if you did need to search on the specifics, a more customized approach would make sense. 

Also, you guys are amazing! :)

**Comment by freekmurze** [comment]
In the config file you can [set the status model](https://github.com/spatie/laravel-model-status/blob/1079f959636292e2bb42ba387f2ccd78774ca763/config/model-status.php#L10). That model can hold any property your heart desires.

(thanks for the compliment :-))
