### ISSUE TITLE
Event on status change

### ISSUE THREAD

**Issue by vpratfr** [spatie/laravel-model-status#28]
Hi,

Do you think events for status changes should be part of the package?

I have this currently implemented on a per-model basis, but wondering if that would be worth including in the package.

Like `StatusUpdated($model, $oldStatus, $newStatus)`

**Comment by freekmurze** [comment]
Seems like a good addition yes, we'd accept a PR for that. Feel free to send one.

Closing the issue now, but If would have any more questions about the functionality, go ahead and comment below.
