### ISSUE TITLE
Querying by intervals

### ISSUE THREAD

**Issue by norotico** [spatie/laravel-model-status#36]
I have an use case that might be somewhat common among dev's using this package, so I'm curious how people have approached this. 

Say I have `products` hasMany `items` (item representing an ordered product). Product can be active or inactive. Then I want to know how many times each product was ordered in the last N days that it's been active.

Of course I can fetch all statuses for each product, iterate them, count days, etc. But I'm looking for a more eloquent/query-builder way with as few queries as possible.

I think it'd be also nice if this package offered something like `$model->statusDuration('status-name')` to easily find out how much time the model has been with the given status.

Opinions?

**Comment by freekmurze** [comment]
I'm thinking that this is not a common enough problem to warrant dedicated function in this package.

You can add functions for this in your own project.

If you do feel there are some functions that warrant a place in this package, feel free to PR them.
