### ISSUE TITLE
QueryBuilder::setStatus does not exitst

### ISSUE THREAD

**Issue by celciuz** [spatie/laravel-model-status#37]
Hi, please help me, i have a something error in my first try at this package. I have insert the UseStatuses in model, but i get error. 

**My controller is :** 

    public function statuses(PinjamRuang $pinjamruang)
    {
        $pinjamruangs = $pinjamruang->where('id',1)->setStatus('pending');
    }

**And I have error :** 
"Method Illuminate\Database\Query\Builder::setStatus does not exist."

**PinjamRuang is my model and I have inserted useHasStatuses like this :** 

use Illuminate\Database\Eloquent\Model;
use Spatie\ModelStatus\HasStatuses;
class PinjamRuang extends Model
{
    use HasStatuses;
    protected $fillable = [
        'user_id', 'ruang_id', 'waktu_mulai', 'waktu_selesai', 'kegiatan', 'lampiran', 
    ];
}

I also do vendor publish like in the tutorial, but the error still come.

**Comment by freekmurze** [comment]
`setStatus` should be called on a model, not on a query.


`$pinjamruang->where('id',1)->first()->setStatus('pending');`
