### ISSUE TITLE
adding causer_id to statuses table

### ISSUE THREAD

**Issue by rapocalypse** [spatie/laravel-model-status#38]
Hi, I'm a pretty newbie on this… is there any way that I could add a causer_id to the statuses table and auto fill it with the logged user id (\Auth::id())?

If you could, please send me any link that points out how to do it, or a sample code that I can use to understand and learn more.

thanks!

RA

**Comment by freekmurze** [comment]
You can achieve this by using your own custom model and [eloquent models events](https://laravel.com/docs/5.6/eloquent).

1. Create a new model class like this (untested);

```php
namespace App\Models;

class YourStatusModel extends \Spatie\ModelStatus\Status

public static function boot()
{
   // this function will automatically be executed by Laravel when a new `Status` is being created.
    static::creating(function(YourStatusModel $status) {
        $status->causer_id = optional(auth()->user())->id;
    });
}
```

2. Set that class in the `status_model` key of the `model-status` config file.

3. Create a migration that adds `caused_id` to the `statuses` table.

4. Profit!

**Comment by devyoudu** [comment]
Just for information: this solution works in Laravel 9 but in the 'YourStatusModel' model it is necessary to inform `parent::boot();` on boot method. Otherwise an exception will be thrown by Laravel. Thanks Freek, big fan here :)
