### ISSUE TITLE
Using another key name than 'model_id'

### ISSUE THREAD

**Issue by vpratfr** [spatie/laravel-model-status#39]
In our app, we use UUIDs as ids.

For consistency within the application, we suffix the foreign key names with _uuid instead of _id as our primary key column is 'uuid'.

We can easily update the migration files to change the $table->morphsTo('model') to use a different name and type for the schema.

However, it is more difficult to let the `HasStatus` trait know about it.

So, currently I am stuck with either :

- Redefining most of the trait (not so great as I would copy-paste all methods including the ones which do not show any issues)
- Sticking with model_id as column name. But does not feel right/consistent when looking at the whole application DB schema.

Possible way to solve it (unless you have a better idea) :

Allow a custom column name within the traits (could be a property which could be set in the class, like private $permissionModelForeignColumn = 'model_uuid'; and check if that propery is set in the relationship method (defaulting to current name if not)

**Comment by vpratfr** [comment]
Similar to https://github.com/spatie/laravel-permission/issues/777 ;)

**Comment by freekmurze** [comment]
I'd accept a PR (fully tested, fully documented) that adds a config option to set the column name for the id.

**Comment by vpratfr** [comment]
Ok. Will do that when I can.

Any preferred name for the config option?

**Comment by freekmurze** [comment]
`model_primary_key_attribute` seems nice.
