### ISSUE TITLE
Many statuses per model?

### ISSUE THREAD

**Issue by PrimozRome** [spatie/laravel-model-status#49]
Can this package assign multiple statuses to an Eloquent model?

For example, typical case scenario in a business application. Let's say we have an Invoice model, which describes an issued invoice. In a multistage business application this model can have multiple statuses at the point of a lifetime of the invoice:

- I can have a general invoice status: Issued, Signed, Sent, etc..
- I can gave a finical status that tells me invoice has been paid or not

Then if we look at order mode can have a similar scenarios. Can have multiple statuses, depending from which side of organisation you are looking at. Marketing people can have its own statuses, production people its own, shipping people its own, and so on...

**Comment by Sinepel** [comment]
Hello,

this point interests me a lot too.
Is it possible ?

Thank you ! :)

**Comment by freekmurze** [comment]
Currently this is not possible and out of scope for this package.

**Comment by palokankare** [comment]
Hi,

I solved this by creating an Eloquent model without table to hold another statuses. I have a Ticket model that has a status. A ticket has also a phase, so I created TicketPhase class.

```php
class Ticket extends Model
{ 
  public function phase()
  {
    return new TicketPhase(['id' => $this->id]);
  }
    ...
}
```

```php
class TicketPhase extends Model
{
    use HasStatuses;

    protected $guarded = [];
    ...
}
```

```php
$ticket = Ticket::find(1);

$ticketPhase = new TicketPhase([id => $ticket->id]);
$ticketPhase->setStatus('pending');

return $ticket->phase()->statuses;
```
