### ISSUE TITLE
Performance improvements?

### ISSUE THREAD

**Issue by ragingdave** [spatie/laravel-model-status#52]
In attempting to use this package, I was unable to get any reasonable performance for searching based on status. Even after adding an index to the name column, I was left with a query that ended up taking 4 seconds to get a paginated list of models with that status. To be fair I have about 750k records with at least half having a status. I guess my question is if there is any other performance improvements that can be had or if this is just the best that can be attained. If nothing can be improved then I would say this package would only be suitable for smaller datasets rather than anything on the larger end.

That being said Love what you guys are doing and probably are using almost every laravel package you guys have made! (Didn't want to be ALL doom and gloom)

**Comment by freekmurze** [comment]
We didn't use this package ourselves on a table with that many records. For the projects we're using it on the performance seems fine.

I do welcome any PR that improves performance.

Thanks for the kind words on our work!
