### ISSUE TITLE
Integrity constraint violation: 1048 Column 'model_id' cannot be null

### ISSUE THREAD

**Issue by tsangaris** [spatie/laravel-model-status#53]
I am trying to use this package to monitor the status of my Orders.

1) My Order model has the HasStatuses trait
2) The statuses table is migrated

In my OrderController I do:

`$order = new Order();`
`$order->description = $request->description;`
`$order->setStatus($request->status_name, $request->status_reason);`

Both $request->status_name and $request->status_reason are coming from a form.

When I try to post the form I get the following error:

**Integrity constraint violation: 1048 Column 'model_id' cannot be null**

As I see from the response the model_type is App\Order which in my mind is the correct value. Why isn't the model_id added into the query when doing $order->setStatus(...)?

Thanks!

**Comment by tsangaris** [comment]
I think I found the reason for not working: First I had to save the model ($order->save();) and then proceed with setting the status to it ($order->setStatus(...);).

**Comment by nguyentranchung** [comment]
Should the problem be closed?
