### ISSUE TITLE
Filter by status using spatie/laravel-query-builder

### ISSUE THREAD

**Issue by Trixpua** [spatie/laravel-model-status#55]
I am trying to use this together the spatie/laravel-query-builder package, how I do to build a scoped filter by status?

I tried something like this, but it doesn't work:

```
    public function scopeStatus($query, $status)
    {
        return Model::currentStatus($status);
    }
```

**Comment by zhaomengqiao** [comment]
Did it work out later?

**Comment by Trixpua** [comment]
> Did it work out later?

To filter by status, just need add a scope filter in 'current_status', like this:

`Filter::scope('status', 'current_status')`
