### ISSUE TITLE
Use with models that have a uuid instead of int

### ISSUE THREAD

**Issue by AlexGodbehere** [spatie/laravel-model-status#56]
Is it possible to use this package with models that have a `uuid` as their ID rather than an `int`? I'm getting the following error when trying to set a status:

```
Illuminate\Database\QueryException : SQLSTATE[01000]: Warning: 1265 Data truncated for column 'model_id' at row 1 (SQL: insert into `statuses` (`name`, `reason`, `model_id`, `model_type`, `updated_at`, `created_at`) values (departed, Departed, 6eff0175-ec09-4ab2-8af1-27bc37230208, App\Flight, 2019-03-24 14:54:39, 2019-03-24 14:54:39))
```

**Comment by AlexGodbehere** [comment]
I've created a migration to convert the `model_id` from `int` to `string, 36`. Is this a legit way to accomplish this or can you see any issues with this approach?

```
public function up()
    {
        Schema::table('statuses', function (Blueprint $table) {
			$table->string('model_id', 36)->change();
        });
    }
```

**Comment by freekmurze** [comment]
Seems good.

**Comment by jayenne** [comment]
If you need UUID for scalabitiy then the ID field with need ot be UUID too.
This owuld require a change/fork to the vendor files too.
