### ISSUE TITLE
[SUGGESTION] SaveManyStatuses 

### ISSUE THREAD

**Issue by andresayej** [spatie/laravel-model-status#60]
Recently while I was using the package I've needed to save/update a bunch of records(10k+ in one go) at the same time and their corresponding statuses. However, I haven’t founded any efficient way of doing that using the package built-in capabilities. So i've come up with this Trait:

https://gist.github.com/andresayej/d265986c38255b3bb4a418fe33bab32b

So, if you use this Trait alongside the `HasStatuses` Trait in your model you can do stuff like this:

```
Post::saveManyStatuses('Draft', ['4', '9', '13', '17']);
```
or 
```
User::saveManyStatuses('Promoted', ['1', '2', '3', '4'], 'Optional reason for promotion status');
```
or 
```
Comment::saveManyStatuses('Review', ['21', '24', '81', '97'], 'Optional reason for review status', 500);
```

@freekmurze is this something worth proceeding if you are willing to include it in the core of the package?

If yes, my roadmap for this feature is:

- Write tests
- Find a way to strip down all eager loaded relationships on the model (if defined in the model's $with array) as to better optimize the performance of the number of queries and the memory usage. (Stumbled upon this myself, so sounds like an edge case for more people )
- Find a way to support SoftDeletes with an optional parameter in the function. Something like: `saveManyStatuses('Deleted', $ids, null, null, true)`
- the default ChunkNumber can be configured from the package config file
- maybe refactor to collections?

**Comment by freekmurze** [comment]
Thank you for suggestion this. I've haven't got a need for this functionality atm and don't want to maintain the code.
