### ISSUE TITLE
Eloquent relations with 

### ISSUE THREAD

**Issue by rhonalchirinos** [spatie/laravel-model-status#61]
How can i to use with eloquent relations with ?
For now this helps me

```php
    // model 
    public function currentStatus()
    {
        return $this->MorphOne(
            $this->getStatusModelClassName(),
            'model',
            'model_type',
            $this->getModelKeyColumnName()
        )
            ->latest('id');
    }
    // controller 
    User::with('currentStatus')->get();
```

**Comment by andresayej** [comment]
What are you trying to achieve exactly?

If you want to get the current (e.g. latest) status for a model when you call: `$model->status` you will do exactly that.

If you want to include it in the toArray of your model you can easily use the $appends property and add it there.
Example:
```
<?php

namespace App;

use Spatie\ModelStatus\HasStatuses;

class User extends Authenticatable
{
    use HasStatuses;

    protected $appends = [
        'status',
    ];

.....
```

**Comment by rhonalchirinos** [comment]
I apologize for the delay, I explain I need to load the states of the users without making n + 1 query, User :: all () run N + 1, also if I do User :: with ('currentStatus') -> get () , adding the currentStatus function that I explain above executes only 2 queries, here an example

**Comment by andresayej** [comment]
@rhonalchirinos 

If you want to eager load the relationship and avoid N+1 queries you can do it like so:
```
User::with('statuses')->get()
``` 

If you want to always eager load that relationship you can add it to the ```$with``` property on the desired model.
Example the `User::class` model:
```
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\ModelStatus\HasStatuses;

class User extends Authenticatable
{
    use Notifiable;
    use HasStatuses;
   /**
     * The relationships that should always be loaded.
     *
     * @var array
     */
    protected $with = [
        'statuses',
    ];

etc...
```
More on the topic can be found here:
https://laravel.com/docs/5.8/eloquent-relationships#eager-loading

> Eager Loading By Default
Sometimes you might want to always load some relationships when retrieving a model. To accomplish this, you may define a $with property on the model:
