### ISSUE TITLE
Is there a way to eager load for an API resource?

### ISSUE THREAD

**Issue by AlexGodbehere** [spatie/laravel-model-status#65]
I've defined an API resource where I want to return the status of the model, but I'm getting an N+1 because it's fetching the status for each model individually. Is there a way to eager load this?

``` php
return [
				'id'                         => $this->id,
				'created_at'                 => $this->created_at,
				'updated_at'                 => $this->updated_at,
				'initiated_by'               => new UserResource($this->initiated_by),
				'amount'                     => $this->amount,
				'icon'                       => $this->icon,
				'reference'                  => $this->reference,
				'status'                     => $this->status,
]
```

**Comment by andresayej** [comment]
@AlexGodbehere 
You can try to always eager load the relationship using the `$with` property in the desired model.
Take a look at this, it might help:
https://github.com/spatie/laravel-model-status/issues/61#issuecomment-550067133
