### ISSUE TITLE
Nova Field

### ISSUE THREAD

**Issue by Paulsky** [spatie/laravel-model-status#70]
Hello,

Thank you for this great package! I would like to use the statuses in a Nova field for my model. I'm not sure how to implement this. I have tried the ['morph fields'](https://nova.laravel.com/docs/3.0/resources/relationships.html#morphone) but I can't seem to render the field.

Thank you in advance!

**Comment by SuhaibKotb** [comment]
+1

**Comment by dennissvu** [comment]
+2

**Comment by Beaudinn** [comment]
+ 1

**Comment by codica-studio** [comment]
+3

**Comment by d0utone** [comment]
Hey Guys,
I created a little Workaround for this with a nova Action (https://nova.laravel.com/docs/1.0/actions/defining-actions.html):
- Create Action with Nova `php artisan nova:action YOUR_ACTION_NAME`
- Use Select Field to determine which Status to set (Can be done in the [fields section](https://nova.laravel.com/docs/1.0/actions/defining-actions.html#action-fields))
- Update Status for all Models selected with the action

Here is my Code for the Action:

`<?php

namespace App\Nova\Actions;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Collection;
use Laravel\Nova\Actions\Action;
use Laravel\Nova\Fields\ActionFields;
use Laravel\Nova\Fields\Select;

class setStatus extends Action
{
    use InteractsWithQueue, Queueable;

    /**
     * Perform the action on the given models.
     *
     * @param  \Laravel\Nova\Fields\ActionFields  $fields
     * @param  \Illuminate\Support\Collection  $models
     * @return mixed
     */
    public function handle(ActionFields $fields, Collection $models)
    {
        foreach ($models as $model) {

            // The normal function to set the Status
            $model->setStatus($fields->status);
        }
    }

    /**
     * Get the fields available on the action.
     *
     * @return array
     */
    public function fields()
    {
        return [
            Select::make('Status')->options([
                'created' => 'DRAFT',
                'published' => 'READY FOR SUBMISSION',
            ])->displayUsingLabels()
        ];
    }
}`

**Comment by Paulsky** [comment]
Please reopen this issue

**Comment by ImJustToNy** [comment]
I'm also interested

**Comment by vbezruchkin** [comment]
Hi,

same topic here. it would be great to have a support in the box. thanks
