### ISSUE TITLE
delete statuses on delte model?

### ISSUE THREAD

**Issue by jayenne** [spatie/laravel-model-status#72]
Hi,
does/can this package kep statuses in sync with model deletions using forgein key assignment? if so, how does it work becasue it's not doing in my app.

if not, what would be the preferred place to get and delete any statuses please?
ty.

**Comment by freekmurze** [comment]
> does/can this package kep statuses in sync with model deletions using forgein key assignment

No, you should do that manually. A good place would be where you delete the model that has statuses

**Comment by jayenne** [comment]
Thanks Freek.
In the insterests of learning, can I ask the reason for not including it? wouldn't it be useful? would it be bad practice or require a messy solution?  other?

**Comment by freekmurze** [comment]
By default, Laravel doesn't delete records that have a polymorphic relation. We just follow the default behaviour.
