### ISSUE TITLE
Accessing status() after a call to setStatus does not give you current status.

### ISSUE THREAD

**Issue by dave0783** [spatie/laravel-model-status#73]
Lets say the current status for my model is "Testing 123".
```
$m = Model::find(1);
echo $m->status;
```
would yield:
```
Testing 123
``` 
as expected. However if you:
```
$m = Model::find(1);
echo $m->status;
$m->setStatus('Testing 1234');
echo $m->status;
```
You would see:
```
Testing 123
Testing 123
```

I realize I could just `$m->load('statuses')` , but it seems like it would be helpful if `setStatus` did this automatically.

**Comment by salehahmedZ** [comment]
Have you tried: 
$m->fresh()->status;

**Comment by dave0783** [comment]
I have not; however that is similar to what I said I could already do.  I’m merely suggesting that setStatus update the status on the model so you don’t have to reload the entire object or a relation.

~Dave

**Comment by AEK-BKF** [comment]
Same Error here !
