### ISSUE TITLE
model_has_statuses doesn't exist

### ISSUE THREAD

**Issue by aliosmanyuksel** [spatie/laravel-model-status#87]
Hello,

I got this error. I think it's a bug.

 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'makales.model_has_statuses' doesn't exist (SQL: select `statuses`.*, `model_has_statuses`.`model_id` as `pivot_model_id`, `model_has_statuses`.`status_id` as `pivot_status_id`, `model_has_statuses`.`model_type` as `pivot_model_type` from `statuses` inner join `model_has_statuses` on `statuses`.`id` = `model_has_statuses`.`status_id` where `model_has_statuses`.`model_id` = 1 and `model_has_statuses`.`model_type` = App\Models\Post limit 1)

Application Name ......................................................................................................................... Laravel  
Laravel Version ........................................................................................................................... 9.25.1  
PHP Version ................................................................................................................................ 8.1.9  
Composer Version ........................................................................................................................... 2.4.0  
Environment ................................................................................................................................ local  
Debug Mode ............................................................................................................................... ENABLED

**Comment by freekmurze** [comment]
Our tests seem to prove that this package works as intended. Could you PR a failing test for us to check?
